apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    dev.azure.com/project-repo: GFT-HelmChart_pt2/helmchart-pt2
    dev.azure.com/build-definition: helmchart-pt2
spec:
  type: service
